# Exercícios NumPy  

Agora que aprendemos sobre NumPy, vamos testar seu conhecimento. Começaremos com algumas tarefas simples, para depois entrarmos nas perguntas mais complicadas.

#### Importe NumPy como np

In [1]:
# Importa a biblioteca NumPy, utilizando o apelido padrão 'np'
import numpy as np

#### Crie uma matriz de 10 zeros

In [2]:
# Cria um array unidimensional (vetor) com 10 elementos, todos inicializados com o valor 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crie uma matriz de 10 ones

In [3]:
# Cria um array com 10 elementos, todos inicializados com o valor 1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crie uma matriz de 10 cincos

In [4]:
# Cria um array com 10 elementos igualmente espaçados entre o início (5) e o fim (5)
np.linspace(5, 5, 10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Crie um array de inteiros de 10 até 50

In [5]:
# Gera um array com uma sequência de números inteiros começando em 10 e indo até 50
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Crie um array dos numeros pares de 10 até 50

In [6]:
# Gera um array começando em 10 e indo até 50, pulando de 2 em 2
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Criei uma matriz 3x3 com valores variando de 0 até 8

In [7]:
# Cria um array unidimensional (vetor) com 9 elementos, de 0 a 8
arr = np.arange(0, 9)

# Reorganiza os dados do array 'arr' em uma nova forma (shape) de 3 linhas e 3 colunas
matriz = arr.reshape((3,3))

# Exibe a matriz
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crie uma matriz identidade 3x3

In [8]:
# Cria uma matriz identidade de ordem 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy para gerar números aleatórios entre 0 e 1

In [9]:
# Gera um array contendo 1 único número aleatório
# O número é extraído de uma distribuição uniforme no intervalo [0, 1)
np.random.rand(1)

array([0.39660692])

#### Use Numpy para gerar um array de 25 números aleatórios tirados de uma distribuição normal.

In [10]:
# Gera um array com 25 números aleatórios extraídos de uma "Distribuição Normal Padrão"
np.random.randn(25)

array([ 0.51958744, -1.95991702, -1.8134433 ,  0.81019236,  0.16338526,
        0.02219497,  0.01035101, -1.52687209,  0.58541368,  0.20862534,
       -0.68417911, -0.25441985, -0.56850164, -0.74141161,  0.42339571,
       -1.10487325,  0.95553898, -0.68376471, -0.21278447,  1.72415659,
       -0.20898515,  0.66032944, -0.13818142,  0.04117471, -0.43311594])

#### Crie a seguinte matriz:

In [11]:
# Cria uma matriz 10x10 com valores que variam de 0.01 a 1.0
np.arange(1, 101).reshape((10, 10)) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Crie um array de tamanho 20 igualmente espaçado entre 0 e 1.

In [12]:
# Cria um array com 20 números igualmente espaçados, começando em 0 e terminando em 1
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexação Numpy e Seleção

Agora você receberá algumas matrizes e será solicitado a replicar as saídas resultantes da matriz:

In [13]:
# Cria uma matriz 5x5 com valores sequenciais de 1 a 25
mat = np.arange(1,26).reshape(5,5)

# Exibe a matriz
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
# '2:' seleciona da linha de índice 2 até o final (linhas 3, 4 e 5)
# '1:' seleciona da coluna de índice 1 até o final (colunas 2, 3, 4 e 5)
mat[2: , 1: ]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
# Acessa o elemento localizado na linha de índice 3 e coluna de índice 4
mat[3, 4]

np.int64(20)

In [16]:
# Extrai uma submatriz das 3 primeiras linhas (índices 0, 1 e 2)
# e da segunda coluna (índice 1)
mat[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [17]:
# Seleciona a última linha da matriz (índice 4)
mat[4, 0: ]

array([21, 22, 23, 24, 25])

In [18]:
# Seleciona todas as linhas a partir do índice 3 até o final
# isso resultará nas duas últimas linhas completas
mat[3: ,0: ]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Agora faça o seguinte

#### Obter a soma de todos os valores no "mat"

In [19]:
# Calcula a soma de todos os elementos contidos na matriz
mat.sum()

np.int64(325)

#### Obter o desvio padrão dos valores em mat

In [20]:
# Calcula o desvio padrão de todos os elementos da matriz
mat.std()

np.float64(7.211102550927978)

#### Obter a soma de todas as colunas em mat

In [21]:
# Calcula a soma de todos os elementos ao longo do eixo 0 (eixo vertical)
mat.sum(axis=0)

array([55, 60, 65, 70, 75])