In [102]:
# chamo a biblioteca numpy e apelido de np
import numpy as np 

Video: Criacao de vetores e arrays e numpy.random

In [103]:
# uma lista é criada
minha_lista = [1, 2, 3]

In [104]:
# Exibe a lista
minha_lista

[1, 2, 3]

In [105]:
# Converte a lista em um array
np.array(minha_lista)

array([1, 2, 3])

In [106]:
# lista de listas
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [107]:
# a lista de listas é convertida em um array bidimensional (matriz).
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
# um array indo de 0 a 9 é criado
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
#  um array de 0 a 9, indo de 2 em 2 é criado
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [110]:
# array com três zeros é criado
np.zeros(3)

array([0., 0., 0.])

In [111]:
# arr recebe um array de três zeros
arr = np.zeros(3)

In [112]:
# exibe o array
arr

array([0., 0., 0.])

In [113]:
# uma matriz de zeros 5x5 é criada
# arr recebe esta matriz
arr = np.zeros((5, 5))

In [114]:
# exibe arr
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [115]:
# uma matriz de zeros 3x3 é criada
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [116]:
# uma matriz identidade 4x4 é criada
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [117]:
# um array indo indo de 0 a 10 e igualmente espaçado é criado
np.linspace(0, 10, 2)

array([ 0., 10.])

In [118]:
# um array indo indo de 0 a 10 e igualmente espaçado é criado
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [119]:
# cria um array de 5 elementos contendo números aleatórios no intervalo de 0 até 1
np.random.rand(5)

array([0.10049493, 0.91385279, 0.31940199, 0.24542254, 0.66925651])

In [120]:
# cria um array de 4 números aleatórios seguindo uma distribuição normal:
np.random.randn(4)

array([ 1.46466306, -1.48040632,  0.73376724, -2.09493578])

In [121]:
# cria um array de 10 números inteiros aleatórios de 0 até 99
np.random.randint(0, 100, 10)

array([57, 21, 39, 71, 67,  2, 34, 92, 50, 52], dtype=int32)

In [122]:
# cria um array de 5 números aleatórios de 0 até 1 e os multiplica por 100
np.random.rand(5) * 100

array([41.66566478, 45.12406653, 29.44399443, 56.91959272, 40.14613961])

In [123]:
# cria um array de 5 números aleatórios de 0 até 1 e os multiplica por 100 e arrendonda
np.round(np.random.rand(5) * 100, 0)

array([21., 63., 59., 47., 96.])

In [124]:
# cria um array de 25 elementos variando de 0 até 1
arr = np.random.rand(25)

In [125]:
# Exibe 'arr'
arr

array([0.8883606 , 0.14980369, 0.69769815, 0.52761694, 0.60863025,
       0.23572296, 0.03821388, 0.82779397, 0.69782433, 0.76159824,
       0.66843731, 0.87791968, 0.6238449 , 0.45867608, 0.14096879,
       0.54075208, 0.88149566, 0.53268403, 0.38099881, 0.73835229,
       0.00627822, 0.61945652, 0.25726629, 0.29130323, 0.655742  ])

In [126]:
# transforma arr em uma matriz 5x5
arr = arr.reshape((5, 5))

In [127]:
# exibe 'arr'
arr

array([[0.8883606 , 0.14980369, 0.69769815, 0.52761694, 0.60863025],
       [0.23572296, 0.03821388, 0.82779397, 0.69782433, 0.76159824],
       [0.66843731, 0.87791968, 0.6238449 , 0.45867608, 0.14096879],
       [0.54075208, 0.88149566, 0.53268403, 0.38099881, 0.73835229],
       [0.00627822, 0.61945652, 0.25726629, 0.29130323, 0.655742  ]])

In [128]:
# retorna as dimensões da matriz
arr.shape

(5, 5)

In [129]:
# retorna o maior valor da matriz arr
arr.max()

np.float64(0.8883605953994814)

In [130]:
# retorna o menor valor da matriz arr
arr.min()

np.float64(0.006278217914197914)

In [131]:
# retorna o índice onde o maior valor da matriz está presente
arr.argmax()

np.int64(0)

In [132]:
# retorna o índice onde o menor valor da matriz está presente
arr.argmin()

np.int64(20)

Video: Indexacao e Fatiamento de arrays

In [133]:
# cria um array com elementos de 0 a 29, indo de 3 em 3 
arr = np.arange(0, 30, 3)

In [134]:
# rxibe 'arr'
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [135]:
# acessa o elemento na quarta posição do array arr
arr[3]

np.int64(9)

In [136]:
# retorna os elementos presentes nos indices 2,3 e 4
arr[2:5]

array([ 6,  9, 12])

In [137]:
# retorna os elementos presentes nos indices 0,1,2,3 e 4
arr[0:5]

array([ 0,  3,  6,  9, 12])

In [138]:
# retorna os elementos presentes nos indices 2,3,4,...,9 (final)
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [139]:
# todos os elementos a partir do indice 2 até final são 100
arr[2:] = 100

In [140]:
# Exibe 'arr'
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [141]:
# cria um array de 0 até 49 e o transforma em uma matriz 5x10
arr = np.arange(50).reshape((5, 10))

In [142]:
# exibe 'arr'
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [143]:
# retorna as dimensões da matriz arr
arr.shape

(5, 10)

In [144]:
# cria uma cópia da matriz arr a partir das suas 3 primeiras linhas
arr2 = arr[:3][:].copy()

In [145]:
# exibe 'arr2'
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [146]:
# todos os elementos de arr2 são 100
arr2[:] = 100

In [147]:
# exibe 'arr2'
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [148]:
# exibe 'arr'
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [149]:
# seleciona as linhas de indices 1,2 e 3 e as colunas de indices 5,6,7,8 e 9
arr[1:4, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [150]:
# array de True ou False, o indice em que o elemento for maior que 50 retorna True, se for menor retorna False
bool = arr > 50

In [151]:
# retorna um array em que os elementos são maiores que 50
arr[bool]

array([], dtype=int64)

In [152]:
# cria um array de 0 a 100, igualmente espaçado
array = np.linspace(0, 100, 30)

In [153]:
# exibe 'array'
array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [154]:
# como é uma array de uma dimensão, é retornado o número de elementos deste array
array.shape

(30,)

In [155]:
# transforma o array em uma matriz 3x10
array = array.reshape(3, 10)

In [156]:
# exibe 'array'
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [157]:
# como arrat, agora, é uma matriz, é retornado suas dimensões
array.shape

(3, 10)

In [158]:
# são selecionadas as linhas de indice 0 e 1 e a coluna de indice 2
array[0:2, 2]

array([ 6.89655172, 41.37931034])

Video: Operacoes com Numpy Arrays

In [159]:
# cria um array de uma dimensão com elementos indo de 0 até 15
arr = np.arange(0, 16)

In [160]:
# Exibe arr
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [161]:
# realiza a soma elemento a elemento
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [162]:
# realiza a subtração elemento a elemento
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [163]:
# realiza a multiplicação elemento a elemento
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [164]:
# realiza a divisão elemento a elemento
arr / arr

C:\Users\doasc\AppData\Local\Temp\ipykernel_9508\923293159.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [165]:
# divide um por zero
1 / 0

ZeroDivisionError: division by zero

In [166]:
# realiza a divisão de 1 por cada elemento do array arr
1 / arr

C:\Users\doasc\AppData\Local\Temp\ipykernel_9508\1433115981.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [167]:
# eleva cada elemento do array arr ao quadrado
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [168]:
# adiciona o valor 100 a cada elemento do array arr
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [169]:
# subtrai o valor 100 a cada elemento do array arr
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [170]:
# multiplica o valor 100 a cada elemento do array arr
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [171]:
# calcula a raiz quadrada de cada elemento do array arr
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [172]:
# calcula a exponencial de cada elemento do array arr
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [173]:
# calcula a média aritmética de todos os elementos do array arr
np.mean(arr)

np.float64(7.5)

In [174]:
# calcula o desvio padrão do array arr
np.std(arr)

np.float64(4.6097722286464435)

In [175]:
# calcula o seno de cada elemento do array arr
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [176]:
# retorna o maior valor contido no array arr
np.max(arr)

np.int64(15)

In [177]:
# retorna o menor valor contido no array arr
np.min(arr)

np.int64(0)

In [178]:
# é o método equivalente à função np.max(arr)
arr.max()

np.int64(15)

In [179]:
# é o método equivalente à função np.min(arr)
arr.min()

np.int64(0)