In [80]:
# Importa a biblioteca NumPy e a apelida como 'np'
import numpy as np 

Video: Criacao de vetores e arrays e numpy.random

In [81]:
# Inicializa uma lista
minha_lista = [1, 2, 3]

In [82]:
# Exibe a lista
minha_lista

[1, 2, 3]

In [83]:
# Converte a lista Python em um array do NumPy
np.array(minha_lista)

array([1, 2, 3])

In [84]:
# Define uma lista de listas
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [85]:
# Converte a lista de listas em um array bidimensional (matriz) do NumPy.
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
# Gera um array NumPy contendo uma sequência de números 
# começando em 0 (inclusivo) e indo até 10 (exclusivo)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
# Gera um array NumPy de 0 a 10 (exclusivo), saltando de 2 em 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [88]:
# Cria um array NumPy preenchido com o valor zero, contendo 3 elementos
np.zeros(3)

array([0., 0., 0.])

In [89]:
# Cria um array NumPy chamado 'arr' preenchido com o valor 0
arr = np.zeros(3)

In [90]:
# Exibe o array
arr

array([0., 0., 0.])

In [91]:
# Cria uma matriz 5x5 (bidimensional) preenchida com zeros
# O resultado é um array com 5 linhas e 5 colunas
arr = np.zeros((5, 5))

In [92]:
# Exibe o array
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [93]:
# Cria uma matriz 3x3 preenchida inteiramente com o valor 1.0.
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [94]:
# Cria uma matriz identidade de tamanho 4x4.
# O resultado é uma matriz com 1s na diagonal principal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [95]:
# Gera um array com uma sequência de valores uniformemente espaçados
np.linspace(0, 10, 2)

array([ 0., 10.])

In [96]:
# Gera um array com uma sequência de valores uniformemente espaçados
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [97]:
# Cria um array de 5 elementos contendo números aleatórios
# segue distribuição uniforme (todos os números têm a mesma chance de aparecer)
np.random.rand(5)

array([0.00808414, 0.89412627, 0.16800045, 0.7145138 , 0.08246285])

In [98]:
# Gera um array de 4 elementos preenchido com números aleatórios
# segue a Distribuição Normal (também conhecida como "Curva de Sino")
np.random.randn(4)

array([-0.20295452, -1.30953339,  0.60171057,  1.17103908])

In [99]:
# Gera um array de 10 números inteiros aleatórios,
# dentro do intervalo de 0 (inclusivo) até 100 (exclusivo)
np.random.randint(0, 100, 10)

array([22, 69, 25, 48, 39, 50, 61, 31, 82, 77], dtype=int32)

In [100]:
# Gera um array de 5 números aleatórios (0 a 1)
# e multiplica cada elemento por 100, resultando em valores entre 0 e 100
np.random.rand(5) * 100

array([62.29227596,  2.59641256, 86.15538131, 87.5556974 , 53.52941352])

In [101]:
# Gera 5 números aleatórios (0 a 1), escala para o intervalo (0 a 100), 
# e arredonda o resultado para o número inteiro mais próximo com 0 casas decimais.
np.round(np.random.rand(5) * 100, 0)

array([84., 62., 19., 57., 64.])

In [102]:
# Cria um array unidimensional de 25 elementos
# preenchido com números aleatórios entre 0.0 e 1.0
arr = np.random.rand(25)

In [103]:
# Exibe 'arr'
arr

array([0.54933427, 0.57633589, 0.54506621, 0.57240957, 0.03711168,
       0.4664945 , 0.0882007 , 0.74004189, 0.8995969 , 0.88006899,
       0.25030991, 0.67050687, 0.48660535, 0.2181732 , 0.36909157,
       0.2935261 , 0.90737554, 0.79903372, 0.54371421, 0.08448317,
       0.59455432, 0.57753818, 0.58112714, 0.14741891, 0.91608912])

In [104]:
# Reorganiza o array unidimensional (de 25 elementos) em uma nova forma
# transformando-o em uma matriz bidimensional de 5 linhas e 5 colunas
arr = arr.reshape((5, 5))

In [105]:
# Exibe 'arr'
arr

array([[0.54933427, 0.57633589, 0.54506621, 0.57240957, 0.03711168],
       [0.4664945 , 0.0882007 , 0.74004189, 0.8995969 , 0.88006899],
       [0.25030991, 0.67050687, 0.48660535, 0.2181732 , 0.36909157],
       [0.2935261 , 0.90737554, 0.79903372, 0.54371421, 0.08448317],
       [0.59455432, 0.57753818, 0.58112714, 0.14741891, 0.91608912]])

In [106]:
# Retorna uma tupla contendo as dimensões do array 'arr'
arr.shape

(5, 5)

In [107]:
# Retorna o valor máximo presente em toda a matriz 'arr'
arr.max()

np.float64(0.9160891151415139)

In [108]:
# Retorna o valor mínimo presente em toda a matriz 'arr'
arr.min()

np.float64(0.037111682009107305)

In [109]:
# Retorna o índice da posição do maior valor encontrado no array
arr.argmax()

np.int64(24)

In [110]:
# Retorna o índice da posição do menor valor encontrado no array
arr.argmin()

np.int64(4)

Video: Indexacao e Fatiamento de arrays

In [111]:
# Cria um array com valores de 0 até (mas não incluindo) 30,
# incrementando de 3 em 3.
arr = np.arange(0, 30, 3)

In [112]:
# Exibe 'arr'
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [113]:
# Acessa o elemento na quarta posição do array 'arr'
arr[3]

np.int64(9)

In [114]:
# Retorna os elementos do índice 2 até o índice 4 (o índice 5 não é incluído)
arr[2:5]

array([ 6,  9, 12])

In [115]:
# O resultado são os 5 primeiros elementos do array
arr[0:5]

array([ 0,  3,  6,  9, 12])

In [116]:
# Retorna do índice 2 até o final do array.
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [117]:
# Modifica o array 'arr' atribuindo o valor 100 
# a todos os elementos a partir do índice 2 até o final
arr[2:] = 100

In [118]:
# Exibe 'arr'
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [119]:
# Cria um array com 50 números (de 0 a 49) 
# e o organiza em uma matriz de 5 linhas e 10 colunas
arr = np.arange(50).reshape((5, 10))

In [120]:
# Exibe 'arr'
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [121]:
# Retorna uma tupla contendo as dimensões do array 'arr'
arr.shape

(5, 10)

In [122]:
# Cria uma cópia independente das 3 primeiras linhas de 'arr'
# O resultado 'arr2' será uma matriz de 3 linhas e 10 colunas (shape: (3, 10))
arr2 = arr[:3][:].copy()

In [123]:
# Exibe 'arr2'
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [124]:
# Atribui o valor 100 a todos os elementos da matriz 'arr2'
# Como 'arr2' é uma cópia independente, o 'arr' original não é afetado
arr2[:] = 100

In [125]:
# Exibe 'arr2'
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [126]:
# Exibe 'arr'
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [127]:
# Seleciona as linhas de 1 a 3 e as colunas de 5 até a última
arr[1:4, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [128]:
# O resultado será True para cada célula onde o valor for maior que 50, e False caso contrário.
bool = arr > 50

In [129]:
# Retornando apenas os elementos 
# onde o valor booleano correspondente é True.
arr[bool]

array([], dtype=int64)

In [130]:
# Cria um array com 30 números igualmente espaçados 
# no intervalo fechado de 0 a 100.
array = np.linspace(0, 100, 30)

In [131]:
# Exibe 'array'
array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [132]:
# Retorna uma tupla contendo as dimensões do 'array'
array.shape

(30,)

In [133]:
# Reorganiza o array 'array' (que tinha 30 elementos) em uma nova estrutura
# Agora ele se torna uma matriz de 2 dimensões com 3 linhas e 10 colunas
array = array.reshape(3, 10)

In [134]:
# Exibe 'array'
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [135]:
# Retorna uma tupla contendo as dimensões do array 'array'
array.shape

(3, 10)

In [136]:
# Acessa o elemento na linha 0, coluna 2 e o elemento na linha 1, coluna 2
array[0:2, 2]

array([ 6.89655172, 41.37931034])

Video: Operacoes com Numpy Arrays

In [137]:
# Cria um array unidimensional com números inteiros de 0 até 15.
arr = np.arange(0, 16)

In [138]:
# Exibe 'arr'
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [139]:
# Realiza a soma elemento a elemento
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [140]:
# Realiza a subtração elemento a elemento
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [141]:
# Realiza a multiplicação elemento a elemento
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [142]:
# Realiza a divisão elemento a elemento
arr / arr

C:\Users\doasc\AppData\Local\Temp\ipykernel_16512\4062765886.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [143]:
# Divide um por zero
1 / 0

ZeroDivisionError: division by zero

In [144]:
# Realiza a divisão de 1 por cada elemento do array 'arr'.
1 / arr

C:\Users\doasc\AppData\Local\Temp\ipykernel_16512\4145822602.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [145]:
# Eleva cada elemento do array 'arr' ao quadrado
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [146]:
# Adiciona o valor 100 a cada elemento do array 'arr'
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [147]:
# Subtrai o valor 100 a cada elemento do array 'arr'
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [148]:
# Multiplica o valor 100 a cada elemento do array 'arr'
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [149]:
# Calcula a raiz quadrada de cada elemento do array 'arr'
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [150]:
# Calcula a exponencial (e^x) de cada elemento do array 'arr'
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [151]:
# Calcula a média aritmética de todos os elementos do array 'arr'
np.mean(arr)

np.float64(7.5)

In [152]:
# Calcula o desvio padrão (standard deviation) dos elementos do array 'arr'
np.std(arr)

np.float64(4.6097722286464435)

In [153]:
# Calcula o seno de cada elemento do array 'arr'
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [154]:
# Retorna o maior valor contido no array 'arr'
np.max(arr)

np.int64(15)

In [155]:
# Retorna o menor valor contido no array 'arr'
np.min(arr)

np.int64(0)

In [156]:
# É o método equivalente à função np.max(arr)
arr.max()

np.int64(15)

In [157]:
# É o método equivalente à função np.min(arr)
arr.min()

np.int64(0)