In [168]:
# chamo a biblioteca numpy e apelido de np
import numpy as np

In [169]:
# criação de um array unidimensional
array_unidimensional = np.array([1, 2, 3, 4, 5, 6])

In [170]:
# por se tratar de uma dimensão, retorna o número de elementos
array_unidimensional.shape

(6,)

In [171]:
# podemos acessar um elemento específico de duas formas: por indices positivos ou negativos

In [172]:
# utilizando indice positivo
array_unidimensional[1]

np.int64(2)

In [173]:
# utilizando indice negativo
array_unidimensional[-1]

np.int64(6)

In [174]:
# podemos, também, acessar os elementos por meio de intervalos: [início : fim (excluido) : passo], onde inicio, fim são os indices

In [175]:
array_unidimensional[1:4]

array([2, 3, 4])

In [176]:
array_unidimensional[1:6:2]

array([2, 4, 6])

In [177]:
array_unidimensional[-4:-1]

array([3, 4, 5])

In [178]:
array_unidimensional[-6:-1:3]

array([1, 4])

In [179]:
# ou por meio de uma lógica
array_unidimensional[array_unidimensional > 3]

array([4, 5, 6])

In [180]:
# criação de um array bidimensional (matriz)
array_bidimensional = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [181]:
# por se tratar de duas dimensão, retorna quantidade de linhas e colunas
array_bidimensional.shape

(3, 3)

In [182]:
array_bidimensional

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [183]:
# acessando um elemento especifico da matriz [linha, coluna]
array_bidimensional[1, 1]

np.int64(5)

In [184]:
# acessando elementos por meio de intervalos

In [185]:
array_bidimensional[1:, 1:]

array([[5, 6],
       [8, 9]])

In [186]:
array_bidimensional[0:, -1]

array([3, 6, 9])

In [187]:
# ou por meio de uma lógica
array_bidimensional[array_bidimensional % 2 == 0]

array([2, 4, 6, 8])

In [188]:
# Podemos, também, criar arrays desse jeito (começo, fim, razão)
array = np.arange(1, 28, 2)

In [189]:
# aqui é um array de uma dimensão
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27])

In [190]:
# porém podemos mudar sua dimensão:
array_reorganizado = array.reshape(2, 7)

In [191]:
# agora temos uma matriz 2x7
array_reorganizado

array([[ 1,  3,  5,  7,  9, 11, 13],
       [15, 17, 19, 21, 23, 25, 27]])

In [192]:
# operações com arrays de uma dimensão
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([3, 6, 9, 12, 15])

In [193]:
# soma
array1 + array2

array([13, 26, 39, 52, 65])

In [194]:
# subtração
array1 - array2

array([ 7, 14, 21, 28, 35])

In [195]:
# multiplicação
array1 * array2

array([ 30, 120, 270, 480, 750])

In [196]:
# divisão
array1 / array2

array([3.33333333, 3.33333333, 3.33333333, 3.33333333, 3.33333333])

In [197]:
# operações com matrizes
matriz1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matriz2 = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [9, 11, 15]
])

In [198]:
# soma
matriz1 + matriz2

array([[ 3,  6,  9],
       [ 5,  8, 11],
       [16, 19, 24]])

In [199]:
# subtração
matriz1 - matriz2

array([[-1, -2, -3],
       [ 3,  2,  1],
       [-2, -3, -6]])

In [200]:
# multiplicação
matriz1 * matriz2

array([[  2,   8,  18],
       [  4,  15,  30],
       [ 63,  88, 135]])

In [201]:
# divisão
matriz1 / matriz2

array([[0.5       , 0.5       , 0.5       ],
       [4.        , 1.66666667, 1.2       ],
       [0.77777778, 0.72727273, 0.6       ]])

In [202]:
# algumas funções

In [203]:
# média da matriz
matriz1.mean()

np.float64(5.0)

In [204]:
# pega o indice do maior elemento da matriz
matriz2.argmax()

np.int64(8)

In [205]:
# soma as coluna da matriz
matriz1.sum(axis = 0)

array([12, 15, 18])

In [206]:
# retorna a soma de todos os elementos da matriz
matriz2.sum()

np.int64(56)

In [207]:
# soma as linhas da matriz
matriz2.sum(axis = 1)

array([12,  9, 35])